%YAML:1.0

imu: 1
num_of_cam: 1

imu_topic: "/mujoco/imu"
image0_topic: "/mujoco/unused/image_raw"
image1_topic: "/mujoco/camera/right/image_raw"
output_path: "/tmp/mujoco_quadrotor/lidar/vins"

cam0_calib: "cam0.yaml"
cam1_calib: "cam1.yaml"
image_width: 640
image_height: 480

estimate_extrinsic: 0
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0, 0.0, 1.0, 0.0,
          -1.0, 0.0, 0.0, 0.0,
          0.0, -1.0, 0.0, 0.03,
          0.0, 0.0, 0.0, 1.0]

multiple_thread: 0

max_cnt: 220
min_dist: 12
freq: 20
F_threshold: 1.0
show_track: 0
flow_back: 0

max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 8.0

acc_n: 0.03
gyr_n: 0.002
acc_w: 0.0003
gyr_w: 0.00003
g_norm: 9.81

estimate_td: 0
td: 0.0

load_previous_pose_graph: 0
pose_graph_save_path: "/tmp/mujoco_quadrotor/lidar/pose_graph"
save_image: 0
